// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.csc.dashboard.admin.web;

import com.csc.dashboard.admin.model.Account;
import com.csc.dashboard.admin.model.BackfillManagement;
import com.csc.dashboard.admin.model.Months;
import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect BackfillManagementController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String BackfillManagementController.create(@Valid BackfillManagement backfillManagement, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("backfillManagement", backfillManagement);
            return "backfillmanagements/create";
        }
        uiModel.asMap().clear();
        backfillManagement.persist();
        return "redirect:/backfillmanagements/" + encodeUrlPathSegment(backfillManagement.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String BackfillManagementController.createForm(Model uiModel,HttpServletRequest httpServletRequest) {
    	String remoteUser = httpServletRequest.getRemoteUser(); 
    	long accCount = Account.findAllAccounts(remoteUser).size();
    	if(accCount==0)
    		return "noTeam";
        uiModel.addAttribute("backfillManagement", new BackfillManagement());
        return "backfillmanagements/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String BackfillManagementController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("backfillmanagement", BackfillManagement.findBackfillManagement(id));
        uiModel.addAttribute("itemId", id);
        return "backfillmanagements/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String BackfillManagementController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel, HttpServletRequest httpServletRequest) {
    	String remoteUser = httpServletRequest.getRemoteUser();
    	if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("backfillmanagements", BackfillManagement.findBackfillManagementEntries(firstResult, sizeNo,remoteUser));
            float nrOfPages = (float) BackfillManagement.countBackfillManagements(remoteUser) / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("backfillmanagements", BackfillManagement.findAllBackfillManagements(remoteUser));
        }
        return "backfillmanagements/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String BackfillManagementController.update(@Valid BackfillManagement backfillManagement, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("backfillManagement", backfillManagement);
            return "backfillmanagements/update";
        }
        uiModel.asMap().clear();
        backfillManagement.merge();
        return "redirect:/backfillmanagements/" + encodeUrlPathSegment(backfillManagement.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String BackfillManagementController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("backfillManagement", BackfillManagement.findBackfillManagement(id));
        return "backfillmanagements/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String BackfillManagementController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        BackfillManagement backfillManagement = BackfillManagement.findBackfillManagement(id);
        backfillManagement.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/backfillmanagements";
    }
    
    @ModelAttribute("accounts")
    public Collection<Account> BackfillManagementController.populateAccounts(HttpServletRequest httpServletRequest) {
    	String remoteUser = httpServletRequest.getRemoteUser();
    	return Account.findAllAccounts(remoteUser);
    }
    
    @ModelAttribute("backfillmanagements")
    public Collection<BackfillManagement> BackfillManagementController.populateBackfillManagements(HttpServletRequest httpServletRequest) {
    	String remoteUser = httpServletRequest.getRemoteUser();
        return BackfillManagement.findAllBackfillManagements(remoteUser);
    }
    
    @ModelAttribute("monthses")
    public Collection<Months> BackfillManagementController.populateMonthses() {
        return Months.findAllMonthses();
    }
    
    String BackfillManagementController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
