// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.csc.dashboard.admin.model;

import java.lang.Integer;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect BackfillManagement_Roo_Jpa_Entity {
    
    declare @type: BackfillManagement: @Entity;
    
    declare @type: BackfillManagement: @Table(name = "backfill_management");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer BackfillManagement.id;
    
    public Integer BackfillManagement.getId() {
        return this.id;
    }
    
    public void BackfillManagement.setId(Integer id) {
        this.id = id;
    }
    
}
