// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.csc.dashboard.admin.model;

import com.csc.dashboard.admin.model.BackfillManagement;
import java.lang.Integer;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BackfillManagement_Roo_Entity {
    
    @PersistenceContext
    transient EntityManager BackfillManagement.entityManager;
    
    @Transactional
    public void BackfillManagement.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void BackfillManagement.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            BackfillManagement attached = BackfillManagement.findBackfillManagement(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void BackfillManagement.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void BackfillManagement.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public BackfillManagement BackfillManagement.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        BackfillManagement merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager BackfillManagement.entityManager() {
        EntityManager em = new BackfillManagement().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long BackfillManagement.countBackfillManagements() {
        return entityManager().createQuery("SELECT COUNT(o) FROM BackfillManagement o", Long.class).getSingleResult();
    }
    
    public static List<BackfillManagement> BackfillManagement.findAllBackfillManagements() {
        return entityManager().createQuery("SELECT o FROM BackfillManagement o", BackfillManagement.class).getResultList();
    }
    
    public static BackfillManagement BackfillManagement.findBackfillManagement(Integer id) {
        if (id == null) return null;
        return entityManager().find(BackfillManagement.class, id);
    }
    
    public static List<BackfillManagement> BackfillManagement.findBackfillManagementEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM BackfillManagement o", BackfillManagement.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
