// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.csc.dashboard.admin.model;

import com.csc.dashboard.admin.model.Account;
import com.csc.dashboard.admin.model.Months;
import java.lang.String;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

privileged aspect BackfillManagement_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "account", referencedColumnName = "id", nullable = false)
    private Account BackfillManagement.account;
    
    @ManyToOne
    @JoinColumn(name = "month", referencedColumnName = "id", nullable = false)
    private Months BackfillManagement.month;
    
    @Column(name = "novient", length = 20)
    private String BackfillManagement.novient;
    
    @Column(name = "emp_serving_notice", length = 200)
    private String BackfillManagement.empServingNotice;
    
    @Column(name = "last_working_date", length = 30)
    private String BackfillManagement.lastWorkingDate;
    
    @Column(name = "replacement_date", length = 30)
    private String BackfillManagement.replacementDate;
    
    @Column(name = "replacement_identified", length = 300)
    private String BackfillManagement.replacementIdentified;
    
    @Column(name = "status", length = 500)
    private String BackfillManagement.status;
    
    public Account BackfillManagement.getAccount() {
        return this.account;
    }
    
    public void BackfillManagement.setAccount(Account account) {
        this.account = account;
    }
    
    public Months BackfillManagement.getMonth() {
        return this.month;
    }
    
    public void BackfillManagement.setMonth(Months month) {
        this.month = month;
    }
    
    public String BackfillManagement.getNovient() {
        return this.novient;
    }
    
    public void BackfillManagement.setNovient(String novient) {
        this.novient = novient;
    }
    
    public String BackfillManagement.getEmpServingNotice() {
        return this.empServingNotice;
    }
    
    public void BackfillManagement.setEmpServingNotice(String empServingNotice) {
        this.empServingNotice = empServingNotice;
    }
    
    public String BackfillManagement.getLastWorkingDate() {
        return this.lastWorkingDate;
    }
    
    public void BackfillManagement.setLastWorkingDate(String lastWorkingDate) {
        this.lastWorkingDate = lastWorkingDate;
    }
    
    public String BackfillManagement.getReplacementDate() {
        return this.replacementDate;
    }
    
    public void BackfillManagement.setReplacementDate(String replacementDate) {
        this.replacementDate = replacementDate;
    }
    
    public String BackfillManagement.getReplacementIdentified() {
        return this.replacementIdentified;
    }
    
    public void BackfillManagement.setReplacementIdentified(String replacementIdentified) {
        this.replacementIdentified = replacementIdentified;
    }
    
    public String BackfillManagement.getStatus() {
        return this.status;
    }
    
    public void BackfillManagement.setStatus(String status) {
        this.status = status;
    }
    
}
