// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.csc.dashboard.admin.model;

import java.io.Serializable;

privileged aspect AuthoritiesPK_Roo_Serializable {
    
    declare parents: AuthoritiesPK implements Serializable;
    
    private static final long AuthoritiesPK.serialVersionUID = 1L;
    
}
