// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.csc.dashboard.admin.model;

import java.lang.String;

privileged aspect BackfillManagement_Roo_ToString {
    
    public String BackfillManagement.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Account: ").append(getAccount()).append(", ");
        sb.append("EmpServingNotice: ").append(getEmpServingNotice()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("LastWorkingDate: ").append(getLastWorkingDate()).append(", ");
        sb.append("Month: ").append(getMonth()).append(", ");
        sb.append("Novient: ").append(getNovient()).append(", ");
        sb.append("ReplacementDate: ").append(getReplacementDate()).append(", ");
        sb.append("ReplacementIdentified: ").append(getReplacementIdentified()).append(", ");
        sb.append("Status: ").append(getStatus());
        return sb.toString();
    }
    
}
