// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.csc.dashboard.admin.model;

import java.lang.String;

privileged aspect UserTeam_Roo_ToString {
    
    public String UserTeam.toString() {
        StringBuilder sb = new StringBuilder();

        return sb.toString();
    }
    
}
